# Generated by Django 3.2.21 on 2023-10-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('you_own', models.CharField(max_length=300)),
                ('business_name', models.CharField(max_length=300)),
                ('business_website', models.CharField(max_length=300)),
                ('social_media_profile', models.CharField(max_length=900)),
            ],
        ),
    ]
